# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o animasi.o player.o enemy.o map.o weapon.o menu.o
LINKOBJ  = main.o animasi.o player.o enemy.o map.o weapon.o menu.o
LIBS     = -L"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/lib" -L"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"D:/SFML-2.4.2/lib" -mwindows -lsfml-audio -lsfml-window -lsfml-graphics -lsfml-system -pg
INCS     = -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/include" -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/include" -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/UNIVERSITASSEBELASMARET/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -pg
CFLAGS   = $(INCS) -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

animasi.o: animasi.cpp
	$(CPP) -c animasi.cpp -o animasi.o $(CXXFLAGS)

player.o: player.cpp
	$(CPP) -c player.cpp -o player.o $(CXXFLAGS)

enemy.o: enemy.cpp
	$(CPP) -c enemy.cpp -o enemy.o $(CXXFLAGS)

map.o: map.cpp
	$(CPP) -c map.cpp -o map.o $(CXXFLAGS)

weapon.o: weapon.cpp
	$(CPP) -c weapon.cpp -o weapon.o $(CXXFLAGS)

menu.o: menu.cpp
	$(CPP) -c menu.cpp -o menu.o $(CXXFLAGS)
